### ISSUE TITLE
Getting error about KeyError: 'fuelType'

### ISSUE THREAD

**Issue by rschoell** [Yannik25/ha-ryd#2]
Hi Yannik, 
I'm glad someone picked up the efforts of getting ryd into HA. 
I've installed your addon through HACS, configured in Yaml and am now getting this error thread:

Error while setting up ryd platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ryd/sensor.py", line 42, in setup_platform
    fetch()
  File "/config/custom_components/ryd/sensor.py", line 40, in fetch
    ryd_adapter.update()
  File "/config/custom_components/ryd/sensor.py", line 71, in update
    self.ryd.fetch()
  File "/usr/local/lib/python3.8/site-packages/pyryd/pyryd.py", line 103, in fetch
    self._ref_data = self._refactored_data(self._raw_data)
  File "/usr/local/lib/python3.8/site-packages/pyryd/pyryd.py", line 108, in _refactored_data
    return {
  File "/usr/local/lib/python3.8/site-packages/pyryd/pyryd.py", line 109, in <dictcomp>
    key: {"value": val(data), "unit": uni}
  File "/usr/local/lib/python3.8/site-packages/pyryd/pyryd.py", line 15, in <lambda>
    "fuel_type": (lambda x: x["fuelType"], None),
KeyError: 'fuelType'

The set fuel type in the app is "Benzin Super". 
Do you know, what's wrong?
thanks
Ralph

**Comment by nielstron** [comment]
Hi Ralph,

please install https://github.com/Yannik25/pyryd locally and try running the example code (`example.py`) and post it here (anonymized, you car plate might be in that data). Probably the field "fuelType" does not exist in your returned data, we might need to check whether it appears elsewhere or just has to be ignored.

**Comment by rschoell** [comment]
Thanks fort he quick answer.
Tried it locally, but still same error comes back:
***@***.***D72BB6.923BE500]

Ralph

**Comment by rschoell** [comment]
Ok, stripped out a line on the pyryd.py:
REFACTOR_DICT = {
**#    "fuel_type": (lambda x: x["fuelType"], None),**


Result (anonymized):
{'examinationDate': '2021-03-01T00:00:00.000Z', 
'lastFuelTopUpTimestamp': '2020-02-11T20:50:41.633Z', 
'batteryLevelMV': 12403, 
'batteryLevelPercent': 69, 
'batteryLevelTimeStamp': '2021-04-07T09:14:54.000Z', 
'recurrences': [], 

'carOdometer': 
{'initialSyncDone': True, 
'syncRequestReason': None, 
'syncTimestamp': '2021-03-26T07:48:19.090Z', 
'syncRequired': False, 
'timestamp': '2021-04-07T06:08:54.994Z', 
'distanceM': 44891288, 
'source': 'MEAS'}, 

'openDtcs': 
{'sampleTime': '2021-04-07T06:00:58.000Z', 
'countOfOpenDtcs': 0, 
'last': None}, 

'fuel': 
{'consumption': {'USER': {'consumedL': 290.12999938964845, 
'distanceM': 19671661, 
'endTime': '2021-04-04T10:30:52.001Z', 
'lastConsumedL': 53.51, 
'lastDistanceM': 1413577, 
'startTime': '2020-01-25T09:43:34.351Z'}, 

'OBD_DONGLE_MAF': 
{'consumedL': 1.6, 
'distanceM': 19192093, 
'endTime': '2021-04-07T06:05:40.000Z', 
'lastConsumedL': 0, 
'lastDistanceM': 156, 
'startTime': '2020-02-11T20:52:30.000Z'}, 

'MEAS': 
{'consumedL': 1.6, 
'distanceM': 19192093, 
'endTime': '2021-04-07T06:05:40.000Z', 
'lastConsumedL': 0, 
'lastDistanceM': 156, 
'startTime': '2020-02-11T20:52:30.000Z'}}, 

'level': 
{'OBD_FUELLEVEL': {'l': 50.65, 
'percent': 84.42, 
'timestamp': '2021-04-07T06:08:53.000Z'}, 
'USER': {'timestamp': '2021-04-07T06:05:40.000Z', 
'percent': 89, 'l': 53.6570939}, 

'MEAS': {'l': 50.65, 
'percent': 84.42, 
'timestamp': '2021-04-07T06:08:53.000Z'}}}, 
'score': {'ecoScore': None}, 

'reportedFuelTotal': {'modificationTimestamp': '2021-04-04T10:55:46.405Z', 
'fuelL': 344.14, 
'measurementPeriod': '2019-03-20T16:02:10.000Z', 
'measurementDistanceM': 19839020, 
'lifetimeConsumption': 0.017346622968271618}, 

'incognito': False, 
'batteryHealth': 'good', 
'estimates': {'estimates': {'current': {'fuel': 0, 'time': 412169, 'distance': 5653338}, 
'estimated': {'fuel': 0, 'time': 1562807, 'distance': 22352999}, 
'estimationPeriod': 'currentYear'}, 

'yearToDate': {'startDate': '2020-12-31T23:00:00.000Z', 
'speedStats': {'timeAbove': {'0': 56966, '10': 19521, '20': 45143, '30': 61794, '40': 60646, '50': 32203, '60': 21773, '70': 23337, '80': 37257, '90': 15386, '100': 10238, '110': 10670, '120': 9752, '130': 3812, '140': 1851, '150': 1140, '160': 454, '170': 227, '180': 0, '190': 0, '200': 0, '210': 0, '220': 0, '230': 0, '240': 0}, 
'distanceAbove': {'0': 30582, '10': 81862, '20': 314892, '30': 589020, '40': 747389, '50': 477754, '60': 387804, '70': 484225, '80': 873365, '90': 399230, '100': 297110, '110': 339124, '120': 335117, '130': 141171, '140': 74149, '150': 49115, '160': 20592, '170': 10838, '180': 0, '190': 0, '200': 0, '210': 0, '220': 0, '230': 0, '240': 0}}, 
'tripCount': 294, 'time': 412169, 'distance': 5653338, 'fuelConsumed': 0, 'accelerations': 58, 'hardBreaks': 46, 'averageSpeed': 49, 'maxSpeed': 179, 'dayTime': 294591, 'dayDistance': 4021099, 'nightTime': 117578, 'nightDistance': 1632239, 'engineStarts': 0, 'engineOffDuration': 56936, 'longStops': 635, 'maxRpm': 5356, 'maxAccelerationMS2': 4.676860346585117, 'maxDecelerationMS2': 6.784913353720693, 'maxThrottlePercent': 8509, 'maxEngineCoolantTemp': 106, 'maxObdSpd': 176, 'longestStraightDrivingDistanceM': 33744.3431372549, 'gpsClimbM': 55551, 'gpsDeclineM': 56076, 'distanceFor60daysM': 3738730}, 
'startDate': '2020-12-31T23:00:00.000Z', 'sampleTime': '2021-04-07T11:58:26.384Z'}, 
'pointsEarned': 0, 'state': 'PARKING', 'parkingLocation': {'address': {'zip': 'xxxxx', 'street': 'xxxxx', 'houseNumber': 'xxxxx', 'deviationM': 22, 'countryCode': 'de', 'city': 'xxxxx'}, 
'timestamp': '2021-04-07T06:05:40.000Z', 'loc': [9.xxxxx, 48.xxxxx], 'addressString': ''}, 
'curLocation': {'timestamp': '2021-04-07T06:05:40.000Z', 'loc': [9.xxxxx, 48.xxxxx]}, 
'fuelTankSizeL': 60, 'distanceSinceLastTopUpM': 0, 'odoTtM': 19839020, 'odoCarM': 44891288, 'licensePlate': 'XXXXX'}
{'examination_date': {'value': datetime.datetime(2021, 3, 1, 0, 0), 'unit': None}, 
'last_fuel_top_up': {'value': datetime.datetime(2020, 2, 11, 20, 50, 41, 633000), 'unit': None}, 
'battery_voltage': {'value': 12.403, 'unit': 'V'}, 
'battery_percentage': {'value': 69, 'unit': '%'}, 'overall_distance': {'value': 44891.288, 'unit': 'km'}}

**Comment by nielstron** [comment]
Hi, thanks for the addition! I will fix the code to handle missing keys, this should handle the issue. Appearently the tool does not return a fuel type in your case...

**Comment by rschoell** [comment]
Great deal, Niels.
Your help is much appreciated. Let me know, how I can help, once it's published.

Ralph

**Comment by Yannik25** [comment]
Hi Ralph,
Please try updating ha-ryd with HACS and try again.

**Comment by rschoell** [comment]
Thanks Yannik,
works as expected.
Any chance, you'll let the user define which values are needed in the config.yaml? I'd be interested in importing current location for instance.

Ralph

**Comment by nielstron** [comment]
The usual approach to this is to simply import everything that would make sense to import by the component. The user will then select what to display when configuring the front-end. Hence, it is planned to extend the [PyRyd component](https://github.com/Yannik25/pyryd/blob/master/pyryd/pyryd.py) in order to provide more data. If you are familiar with some basics of python, feel free to join! :)

**Comment by Yannik25** [comment]
closing this issue as there is already a proposal by nielstron for the device tracker
